import type { AppOpenAPI } from "./types.js";
import packageJson from '../../package.json' with { type: 'json' };

export default function configureOpenAPI(app: AppOpenAPI) {
    app.doc('/openapi.json', {
        openapi: '3.0.0',
        info: {
            version: packageJson.version,
            title: 'My API',
            description: 'API documentation generated by OpenAPIHono',
        },
    });
}